/* first_class.c generated by valac 0.56.0, the Vala compiler
 * generated from first_class.vala, do not modify */

/* class derived from GObject */

#include <glib-object.h>
#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_BASIC_SAMPLE (basic_sample_get_type ())
#define BASIC_SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BASIC_SAMPLE, BasicSample))
#define BASIC_SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BASIC_SAMPLE, BasicSampleClass))
#define IS_BASIC_SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BASIC_SAMPLE))
#define IS_BASIC_SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BASIC_SAMPLE))
#define BASIC_SAMPLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BASIC_SAMPLE, BasicSampleClass))

typedef struct _BasicSample BasicSample;
typedef struct _BasicSampleClass BasicSampleClass;
typedef struct _BasicSamplePrivate BasicSamplePrivate;
enum  {
	BASIC_SAMPLE_0_PROPERTY,
	BASIC_SAMPLE_NUM_PROPERTIES
};
static GParamSpec* basic_sample_properties[BASIC_SAMPLE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _BasicSample {
	GObject parent_instance;
	BasicSamplePrivate * priv;
};

struct _BasicSampleClass {
	GObjectClass parent_class;
};

static gpointer basic_sample_parent_class = NULL;

VALA_EXTERN GType basic_sample_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (BasicSample, g_object_unref)
VALA_EXTERN void basic_sample_run (BasicSample* self);
VALA_EXTERN BasicSample* basic_sample_new (void);
VALA_EXTERN BasicSample* basic_sample_construct (GType object_type);
static GType basic_sample_get_type_once (void);
static gint _vala_main (gchar** args,
                 gint args_length1);

void
basic_sample_run (BasicSample* self)
{
	FILE* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Hello World\n");
}

BasicSample*
basic_sample_construct (GType object_type)
{
	BasicSample * self = NULL;
	self = (BasicSample*) g_object_new (object_type, NULL);
	return self;
}

BasicSample*
basic_sample_new (void)
{
	return basic_sample_construct (TYPE_BASIC_SAMPLE);
}

static void
basic_sample_class_init (BasicSampleClass * klass,
                         gpointer klass_data)
{
	basic_sample_parent_class = g_type_class_peek_parent (klass);
}

static void
basic_sample_instance_init (BasicSample * self,
                            gpointer klass)
{
}

static GType
basic_sample_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BasicSampleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) basic_sample_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BasicSample), 0, (GInstanceInitFunc) basic_sample_instance_init, NULL };
	GType basic_sample_type_id;
	basic_sample_type_id = g_type_register_static (G_TYPE_OBJECT, "BasicSample", &g_define_type_info, 0);
	return basic_sample_type_id;
}

GType
basic_sample_get_type (void)
{
	static volatile gsize basic_sample_type_id__once = 0;
	if (g_once_init_enter (&basic_sample_type_id__once)) {
		GType basic_sample_type_id;
		basic_sample_type_id = basic_sample_get_type_once ();
		g_once_init_leave (&basic_sample_type_id__once, basic_sample_type_id);
	}
	return basic_sample_type_id__once;
}

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	BasicSample* sample = NULL;
	BasicSample* _tmp0_;
	gint result;
	_tmp0_ = basic_sample_new ();
	sample = _tmp0_;
	basic_sample_run (sample);
	result = 0;
	_g_object_unref0 (sample);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

