/* my_first_program.c generated by valac 0.56.0, the Vala compiler
 * generated from my_first_program.vala, do not modify */

#include <glib.h>

static void _vala_main (void);

static void
_vala_main (void)
{
	g_print ("My first Vala program!\n");
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

